doctrine_mongodb:
    auto_generate_proxy_classes: '%kernel.debug%'
    auto_generate_hydrator_classes: '%kernel.debug%'
    connections:
        default:
            server: 'mongodb://%mongodb_user%:%mongodb_password%@%mongodb_server%:%mongodb_port%'
            #server: 'mongodb://%mongodb_server%:%mongodb_port%'
            #server: '%mongodb_uri%'
            options: {}
    default_database: '%mongodb_database%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/App/Document'
                    prefix: App\Document\
                    alias: App
                AppMainBundle:
                    is_bundle: true
                    type: annotation
                    dir: 'Document'
                    prefix: App\MainBundle\Document\
                    alias: AppMainBundle
                ImportExportBundle:
                    is_bundle: true
                    type: annotation
                    dir: 'Document'
                    prefix: Andchir\ImportExportBundle\Document\
                    alias: ImportExportBundle
