swiftmailer:
    url: 'smtp://%mailer_host%:%mailer_port%?encryption=%mailer_encryption%&auth_mode=%mailer_auth_mode%&username=%mailer_user%&password=%mailer_password%'
    spool: { type: 'memory' }
    logging: true
